### ISSUE TITLE
Implement behaviors (Behavior.md)

### ISSUE THREAD

**Issue by Ernest314** [ErythroGuild/ClippyAssist#18]
## single animation, multiple triggers
- **Alert**
	- [x] raid warning
	- [ ] paragon chest complete (#19)
	- [ ] received zone quest (legion/bfa assaults) (#31)
	- [x] readycheck
	- [x] role check
- **CheckingSomething**
	- [ ] encounter journal open (#33)
	- [ ] reading TRP/MRP (#34)
- **Congratulate**
	- [x] raid boss kill
	- [x] key timed (#22)
	- [ ] rare elite killed
	- [ ] received AH mail
	- [x] quest completed
	- [x] island finished
	- [x] warfront complete
	- [x] received achievement
	- [ ] reached reputation level
	- [x] level up
	- [x] resurrected
	- [x] duel won (#23)
	- [ ] crafting complete
	- [x] new mount
	- [x] new pet
	- [x] new toy
	- [ ] new appearance set
	- [x] barbershop finished
	- [ ] all battlepets healed
- **EmptyTrash**
	- [x] died
	- [ ] key failed (#22)
	- [x] raid boss wipe
	- [ ] duel lost (#23)
	- [x] deleted item
- **Explain**
	- [ ] weakaura speech bubble (while idle)
- **GetAttention**
	- [x] going afk
	- [ ] afk logout starts
- **GoodBye**
	- [ ] casting hearth
	- [ ] casting teleport
- **Greeting**
	- [x] load
- **Hide**
	- [ ] cast invisibility
	- [ ] cast stealth
- **Print**
	- [ ] export WeakAura
- **Processing**
	- [ ] viewing LFG applicants
- **Searching**
	- [ ] viewing LFG groups
- **SendMail**
	- [x] mail sent
	- [ ] trade complete
- **Show**
	- [ ] exit invisibility
	- [ ] exit stealth
	- [ ] cancel logout
- **Wave**
	- [x] interact with frame

## single trigger, multiple animations
- [x] Idle
	- *GetArtsy*
	- *GetAttention*
	- *Look`{direction}`*
	- *Print*
- [ ] Aggro drop (e.g. fade, feign death)
	1. *Hide*
	2. *Show*
- [x] Pull timer
	1. *GetAttention*
	2. *Gesture`{direction}`* (towards center of screen)
	3. *Look`{direction}`* (towards center of screen)
- [ ] Log out (timer)
	1. *Wave1*
	2. *Save*
	3. *Print*
	4. *GoodBye*

**Comment by Ernest314** [comment]
The rest of these will be implemented in their own issues; they're not critical for v1.0 release.
